# syntax=docker/dockerfile:1
FROM php:7.4-fpm-alpine3.16

# 安装 PHP 扩展及其依赖
RUN apk update && apk add --no-cache \
    freetype \
    libpng \
    libjpeg-turbo \
    freetype-dev \
    libpng-dev \
    libjpeg-turbo-dev \
    icu \
    icu-dev \
    icu-libs \
    libwebp \
    libwebp-dev \
    libzip \
    libzip-dev \
    autoconf \
    gcc \
    make \
    musl-dev \
    pcre-dev \
    php7-pear \
    php7-dev \
    nginx \
    supervisor \
    # 配置和安装 PHP 扩展
    && docker-php-ext-configure gd --with-freetype --with-jpeg --with-webp \
    && docker-php-ext-install gd \
    && docker-php-ext-install sockets bcmath intl mysqli pdo pdo_mysql zip \
    && pecl install redis swoole-4.8.12 yac-2.3.1 yaf-3.3.5 \
    && docker-php-ext-enable redis swoole yac yaf \
    && cd /usr/src/swoole_orm && \
        phpize && \
        chmod +x ./configure && \
        ./configure --with-php-config=/usr/local/bin/php-config && \
        make && make install && \
        docker-php-ext-enable swoole_orm \
    && cd /usr/src/ycdatabase/ycdatabase_extension && \
        phpize && \
        chmod +x ./configure && \
        ./configure --with-php-config=/usr/local/bin/php-config && \
        make && make install && \
        docker-php-ext-enable ycdatabase \
    # 清理不再需要的包和缓存
    && apk del --no-cache freetype-dev libpng-dev libjpeg-turbo-dev autoconf gcc make musl-dev pcre-dev php7-pear php7-dev \
    && rm -rf /var/cache/apk/* /usr/src/swoole_orm /usr/src/ycdatabase \
    # 确保套接字目录存在，并设置权限
    && mkdir -p /var/run/php && chown www-data:www-data /var/run/php \
    # 确保环境日志目录存在，并设置权限
    && mkdir -p /var/log && find /var/log -type d -exec chmod 755 {} \;


# 复制 php-fpm , Supervisor 配置文件
COPY conf/nginx.conf /etc/nginx/nginx.conf
COPY conf/default.conf /etc/nginx/conf.d/default.conf
COPY conf/www.conf /usr/local/etc/php-fpm.d/www.conf
COPY conf/supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY conf/yaf.ini /usr/local/etc/php/conf.d/yaf.ini

# 设置工作目录
WORKDIR /opt/jammyfm/www/

# 暴露 8080 端口
EXPOSE 8080

# 设置启动命令，启动php-fpm 和 nginx
CMD ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisor/conf.d/supervisord.conf"]

